### ISSUE TITLE
Streaming is not working on M1 mac browsers & Postman

### ISSUE THREAD

**Issue by Sahas** [vercel-labs/ai#113]
We tested the SDK in vercel edge on various devices using the exact code provided in the documentation. Here are the findings
1.  Apple M1 Mac browsers - Response is not streaming. 
2. Android chrome - Working
3. Windows browsers - Working
4. Mac with Intel chip - working
5. iOS browsers - working
6. Postman - Not working

Is there a bug in SDK or is there any special config we should use to enable streaming on the above devices?

**Comment by shuding** [comment]
This is strange. Browsers should behave the same on different chips as we're only doing a `fetch` request, nothing depends on the device type. Would be great that if you can provide more info, like console/network errors.

Personally I'm on a M1 chip and I can't reproduce this.

**Comment by Itsnotaka** [comment]
This happens to me as well. I found it most disturbing for openAI function callback considering it will not return using token but you need to read the completion json.

Related: issue 97

**Comment by claritise** [comment]
I am using a M2 max MBP and it's working for me on both chrome and safari on the latest version of ventura. What is the issue you are getting?

**Comment by Itsnotaka** [comment]
Maybe it's a langchain specific problem but the onCompletion callback is not working when other two callback work normally.

**Comment by claritise** [comment]
What version are you using? I am currently using 0.0.89

**Comment by Itsnotaka** [comment]
Using 0.0.95

**Comment by Sahas** [comment]
Looks like some temporary issue. I restarted my system & turned off our company vpn & it's working fine now.

**Comment by Sahas** [comment]
Closing this as I can't reproduce

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported behavior was attributed to a temporary local/VPN environment issue, with no reproducible AI SDK failure established. This is best treated as a resolved support report rather than a bug.

### Evidence
- The reporter initially observed missing streaming on M1 browsers and Postman.
- Maintainers and other users could not reproduce the behavior on M1/M2 Macs.
- The reporter said streaming worked after restarting and disabling a company VPN, then closed the issue as unreproducible.
