### ISSUE TITLE
Nuxt: Clicking the "Deploy" vercel button on examples doc does not correctly stream the data

### ISSUE THREAD

**Issue by dosstx** [vercel-labs/ai#133]
Testing out the Nuxt version and clicking the "Deploy" button [here](https://github.com/vercel-labs/ai/tree/main/examples/nuxt-openai) creates and deploys the Nuxt version of the AI chat bot to Vercel server, but does not stream the data response. Only the full response is shown at once. I wanted to quickly test the chatbot demo but I guess I need to manually set up and configure everything, instead? Thanks for any clarification.

This may be due to the fact this deployment template does not include vercel edge preset. If I set nuxt config to vercel edge and deploy, it causes 502 gateway error [see this issue](https://github.com/vercel-labs/ai/issues/135)

**Comment by dosstx** [comment]
Same as: https://github.com/vercel-labs/ai/issues/135

Closing this one.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **Medium**

### Rationale
The reported failure concerns the configuration and deployed behavior of a runnable Nuxt example/template rather than the documented AI SDK API itself. Despite being marked as a duplicate, it contains a concrete request to correct the example deployment.

### Evidence
- The Nuxt example deployed through its Vercel button returns the full response at once instead of streaming.
- The reporter attributes the problem to configuration in the deployment template, specifically the missing Vercel Edge preset.
- The issue was closed as duplicating #135.
