### ISSUE TITLE
Feedback for “useCompletion”

### ISSUE THREAD

**Issue by FacundoLucci** [vercel-labs/ai#136]
Should it be import useCompletion in the svelte code snippet rather that useChat?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This reports a likely typo in documentation rather than a failure in the SDK's runtime behavior.

### Evidence
- The `useCompletion` documentation's Svelte snippet appears to import `useChat` instead of `useCompletion`.
- The requested change is limited to correcting a docs code snippet.
