### ISSUE TITLE
Could more context be passed to stream callbacks?

### ISSUE THREAD

**Issue by wadefletch** [vercel-labs/ai#141]
In creating useful stream callbacks, it would be helpful to carry some additional context about the initial request (model, hyperparameters, prompt) to be used in logging (etc) in the callback. 

I'd be open to creating a PR here if y'all at Vercel are interested.

**Comment by shuding** [comment]
Yep this makes sense, feel free to open a PR for it!

**Comment by shuding** [comment]
#193 should address this.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API enhancement request to provide stream callbacks with additional request context, rather than a report of existing behavior failing.

### Evidence
- The issue requests passing additional initial-request context—model, hyperparameters, and prompt—to stream callbacks.
- The requested context would enable logging and other callback uses; no broken or contradictory existing behavior is reported.
- A maintainer agreed with the enhancement and indicated that PR #193 should address it.
