### ISSUE TITLE
Next JS starter Template gives me an 500 status code internal Error 

### ISSUE THREAD

**Issue by AhmadSaman** [vercel-labs/ai#147]
After doing all the steps that are mentioned [here](https://github.com/vercel-labs/ai/tree/main/examples/next-openai) and generating my API key gives me an error

![image](https://github.com/vercel-labs/ai/assets/55833403/b39af5c3-c6d6-4074-92f9-a55b86abd959)

I didn't change anything inside the [code](https://github.com/AhmadSaman/questionAI)

**Comment by karlbateman** [comment]
Looking at the error response, I can see a `429` error code from the OpenAI API.

Related: #144

**Comment by tbrasington** [comment]
Same but adding billing details to OpenAi resolved it for me.

**Comment by shuding** [comment]
Should be related to #144, I'll close this one and track it there to see how we can expose the original error from OpenAI in a better way. 👍

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports broken error propagation in the starter: an upstream OpenAI 429 is converted into an opaque 500/unhandled runtime error. Although this issue was closed as related to another report, it describes a concrete current-behavior failure.

### Evidence
- The unchanged Next.js starter returns a 500 error and an unhandled HTML runtime error.
- The underlying OpenAI response was a 429, but that original provider error was not exposed clearly.
- A maintainer linked the issue to #144 and said they would track how to expose the original OpenAI error better.
