### ISSUE TITLE
Could not resolve "crypto" deployed in Vercel with SvelteKit Edge Runtime

### ISSUE THREAD

**Issue by johnreyev** [vercel-labs/ai#156]
Hi, first of all I want to express my gratitude for this SDK library. I migrated all my code from implementing streaming from scratch to this. Now, when I tried to deploy to Vercel with SvelteKit Edge Runtime I'm getting this issue in the deployment:

```
Run npm run preview to preview your production build locally.
--
11:37:54.638 |  
11:37:54.638 | > Using @sveltejs/adapter-vercel
11:37:54.708 | ✘ [ERROR] Could not resolve "crypto"
11:37:54.709 |  
11:37:54.709 | .svelte-kit/output/server/chunks/index5.js:3:19:
11:37:54.709 | 3 │ import crypto from "crypto";
11:37:54.709 | ╵                    ~~~~~~~~
11:37:54.709 |  
11:37:54.709 | The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

It successfully builds locally. I search my code and there's no `import crypto from "crypto"` there and looking at the local build files it seems to be pointing to this AI SDK i.e. `import { u as useChat } from "../../../chunks/index5.js";` but still I can't find `import crypto from "crypto"` in the built file.

Thanks in advance

**Comment by johnreyev** [comment]
Was able to fix by changing adapter from `'@sveltejs/adapter-vercel'` to `'@sveltejs/adapter-auto'`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete deployment failure when using the AI SDK with SvelteKit on Vercel Edge Runtime, rather than requesting a new capability.

### Evidence
- Deploying a SvelteKit app using the Vercel Edge Runtime fails because the generated server bundle imports Node's built-in "crypto" module.
- The reporter traced the generated chunk to the AI SDK's useChat import.
- Switching from @sveltejs/adapter-vercel to @sveltejs/adapter-auto avoids the failure, indicating a runtime or bundling compatibility issue.
