### ISSUE TITLE
Add wider support for `fetch` parameters including `credentials`

### ISSUE THREAD

**Issue by jorilallo** [vercel-labs/ai#159]
Currently only additional headers are allowed to be passed to `fetch` alongside the URL. Unfortunately it's not possible to utilize cookie based authentication with `credentials` option so I would love to see ability to pass other options for `fetch`.

**Comment by MaxLeiter** [comment]
Fixed in #222

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for an expansion of the API to support a previously unavailable fetch option, rather than reporting a failure of documented behavior.

### Evidence
- The issue requests support for additional `fetch` options, specifically `credentials`, to enable cookie-based authentication.
- A maintainer agreed to add a `credentials` field to the hooks and invited a PR.
- A later comment states the capability was implemented in #222.
