### ISSUE TITLE
"Unhandled runtime error"—best practices for error handling in API routes?

### ISSUE THREAD

**Issue by GLips** [vercel-labs/ai#179]
If your backend throws an error before sending the initial response, it looks like the generator function responsible for grabbing the response inside the `useCompletion` hook just keeps chugging along, even though the response isn't streamable. This throws an error I seem to be unable to try/catch by e.g. wrapping my `complete` call.

<img width="973" alt="CleanShot 2023-06-20 at 15 52 19@2x" src="https://github.com/vercel-labs/ai/assets/842883/690a295f-7266-4155-b621-7b1bb10f0a54">

Is there another way to do this?

**Comment by shuding** [comment]
Hi! You need to wrap a try-catch and `await` the `complete` call:

```js
try {
  const completion = await complete(...)
} catch (err) {
  // ...
}
```

**Comment by GLips** [comment]
`await` was the missing ingredient. Thank you!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was a usage/support question caused by not awaiting a promise, not a failure in the SDK or a request to change documentation, examples, or product behavior.

### Evidence
- The reporter asks how to catch an error from the asynchronous `complete` call.
- A maintainer explains that `complete(...)` must be awaited inside `try/catch`.
- The reporter confirms that adding `await` resolved the problem.
