### ISSUE TITLE
Couldn't find any versions for "ai" that matches "2.1.5" /  Error: Command "yarn install" exited with 1

### ISSUE THREAD

**Issue by zenchantlive** [vercel-labs/ai#180]
<html>
<body>

Running build in Cleveland, USA (East) – cle1
--
20:27:32.694 | Cloning github.com/zenchantlive/ai-next-huggingface (Branch: main, Commit: 5d35eb1)
20:27:32.928 | Previous build cache not available
20:27:33.206 | Cloning completed: 511.797ms
20:27:33.325 | Running "vercel build"
20:27:33.849 | Vercel CLI 30.2.3
20:27:34.079 | Installing dependencies...
20:27:34.371 | yarn install v1.22.17
20:27:34.396 | info No lockfile found.
20:27:34.401 | [1/4] Resolving packages...
20:27:35.255 | error Couldn't find any versions for "ai" that matches "2.1.5"
20:27:35.256 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
20:27:35.278 | Error: Command "yarn install" exited with 1
20:27:35.720 | BUILD_UTILS_SPAWN_1: Command "yarn install" exited with 1

</body>
</html>

**Comment by ahmadrosid** [comment]
The latest version published on [npm package is 2.1.3](https://www.npmjs.com/package/ai?activeTab=versions) you should change your package version to that version.

```
    "ai": "^2.1.3",
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a dependency-version configuration/support issue rather than broken AI SDK behavior or a request to change the SDK, documentation, or examples.

### Evidence
- Yarn fails because the project requests `ai` version `2.1.5`, which was not published on npm.
- The comment advises changing the dependency to the available `ai` version `^2.1.3`.
