### ISSUE TITLE
Receive Chat ID in API Function

### ISSUE THREAD

**Issue by zzulanas** [vercel-labs/ai#203]
## Issue
For storing conversations in a DB, I'd like to retrieve the chat ID in the request so I can work with it in the back-end so it's easier to store conversations.

### Solution
- Maybe update the body of the SWR Mutation to include the `chatId` as well?

**Comment by MaxLeiter** [comment]
Can you use the `body` or `headers` params supported by `useChat` / `useCompletion`? 

https://sdk.vercel.ai/docs/api-reference/use-chat

```
const {
...
  } = useChat({
    api: '/api/chat',
    body: {
        chatId: chatId
    }
 })
 ```

**Comment by zzulanas** [comment]
@MaxLeiter oh so true bestie, I should really pay attention to the docs more haha.

thanks for pointing that out 👍

**Comment by zzulanas** [comment]
actually I'm having a bit of trouble referencing the `chatId` provided by the hook. I know that the `id` exists on the options, or else it will be randomly generated, should I randomly generate it clientside like this then?
```ts
const chatId = uuidv4();
  const { messages, input, handleInputChange, handleSubmit, isLoading } =
    useChat({
      api: "/api/search-func",
      body: {
        chatId: chatId,
      },
    });
    ```

**Comment by MaxLeiter** [comment]
If you want to override the hook's internal ID you can use the `id` param:

```
  useChat({
      api: "/api/search-func",
      id: chatId,
      body: {
       // use this in your endpoint
        chatId: chatId,
      },
 ```

**Comment by zzulanas** [comment]
If I override the ID my conversation loses its state, is there no way I can access the hooks internal ID on the request? Sorry if I'm missing something, but if I try the approach I just seem to lose rendering of my messages.

**Comment by cipcap** [comment]
> If I override the ID my conversation loses its state, is there no way I can access the hooks internal ID on the request? Sorry if I'm missing something, but if I try the approach I just seem to lose rendering of my messages.

is there? this issue should not have been closed....

**Comment by MaxLeiter** [comment]
@Cenrax which client-side framework are you using?

**Comment by Vialc** [comment]
@MaxLeiter with Next.js is same problem. Body is undefined

**Comment by BannMe** [comment]
Hey I ran into this same issue and you access the body not via `const {messages, body}` but through the key you set in the body. Here is an example i got working locally.

Client Side
`  const { messages, input, handleInputChange, handleSubmit, stop, isLoading } =
    useChat({
      api: "/api/generate",
      initialMessages: initialMessages,
      body: { yo: "hey" },
    });`

Server Side
`export default async function handler(req) {
  const { messages, yo } = await req.json();
  console.log(yo);`

I was able to determine the structure of the req via `const data = await req.json();`

Hope this helps! I'll defer to @MaxLeiter and the vercel team to determine if this is expected or not, but you should be unblocked now.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API enhancement to expose or automatically send useChat's internal chat ID. The discussion includes usage difficulties, but does not establish a failure of promised existing behavior.

### Evidence
- The reporter asks for the hook's internally generated chat ID to be included in API requests for database persistence.
- A maintainer notes that callers can pass a custom value through useChat's existing body and id options.
- The reporter clarifies that they want access to the internal ID rather than supplying their own; no existing documented guarantee is shown to be broken.
- Later comments clarify that custom body fields are flattened into the request JSON and can be read by their key.
