### ISSUE TITLE
Couldn't find any versions for "ai" that matches "2.1.8"

### ISSUE THREAD

**Issue by holdenmatt** [vercel-labs/ai#214]
I wanted to play with the new `ai` sdk, so I tried deploying an example from [here](https://github.com/vercel-labs/ai/tree/main/examples/next-langchain).

It fails to deploy because it's referencing version 2.1.8, which isn't in npm yet.
```
[1/4] Resolving packages...
error Couldn't find any versions for "ai" that matches "2.1.8"
```

Cloning locally, I get the same result. It builds if I change to ai version "2.1.7".

There are some past reports of this [here](https://github.com/vercel-labs/ai/issues/110) and [here](https://github.com/vercel-labs/ai/issues/82), but looks like it's still an issue.

**Comment by EduardoFazolo** [comment]
> I wanted to play with the new `ai` sdk, so I tried deploying an example from [here](https://github.com/vercel-labs/ai/tree/main/examples/next-langchain).
> 
> It fails to deploy because it's referencing version 2.1.8, which isn't in npm yet.
> 
> ```
> [1/4] Resolving packages...
> error Couldn't find any versions for "ai" that matches "2.1.8"
> ```
> 
> Cloning locally, I get the same result. It builds if I change to ai version "2.1.7".
> 
> There are some past reports of this [here](https://github.com/vercel-labs/ai/issues/110) and [here](https://github.com/vercel-labs/ai/issues/82), but looks like it's still an issue.

As of today, June 23rd 2023, the version "2.1.8" really isn't available [at npm](https://www.npmjs.com/package/ai?activeTab=versions) yet.

If you want to run the project locally, I'll make a little step-by-step as I was struggling with it myself:
1. Delete 'node_modules' and uninstall the 'ai' package from your project
2. Clone the repository to the directory of your current project
3. `cd` the packages repository: `....\ai\packages\core\`
4. Run `pnpm install` inside the **cloned repository**
5. After installing the packages, go back to your project's repository and run `pnpm link .\ai\packages\core\`
6. Now run `pnpm install`

This is how I managed to make it work from a local repository, but let me know if you run into any problems

**Comment by MaxLeiter** [comment]
This should be resolved once the latest actions finish. We're still working on our release flow - thanks for the report!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
This reports a runnable example that could not install because it referenced a package version not yet published. The affected artifact is the example project rather than SDK behavior.

### Evidence
- The `next-langchain` example referenced unpublished `ai@2.1.8`, causing dependency installation and deployment to fail.
- The reporter confirmed the example builds after changing its dependency to `ai@2.1.7`.
- A maintainer said the problem would resolve after the release actions finished, indicating no AI SDK runtime behavior defect.
