### ISSUE TITLE
Docs Menu Duplicated

### ISSUE THREAD

**Issue by skorfmann** [vercel-labs/ai#218]
![Screenshot 2023-06-24 at 13 23 57](https://github.com/vercel-labs/ai/assets/136789/c701a317-38f3-4140-94b6-4ab02e66736b)

The `docs` section towards the bottom is odd and links are broken. Looks like duplication.

**Comment by MaxLeiter** [comment]
This should be resolved. Thanks!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete malfunction in the existing documentation site navigation rather than requesting new documentation content.

### Evidence
- The documentation sidebar displayed a duplicated “docs” section.
- The duplicated section contained broken links.
- A maintainer confirmed the issue was resolved.
