### ISSUE TITLE
Docs 404 Page

### ISSUE THREAD

**Issue by altechzilla** [vercel-labs/ai#220]
**Broken Link**: https://sdk.vercel.ai/docs/api-reference/streamingtextresponse

**Linked Here**:

![image](https://github.com/vercel-labs/ai/assets/8274669/0d702329-40db-4ff1-beb6-060e83cecb2f)

**Source**: https://sdk.vercel.ai/docs/guides/openai

**Comment by MaxLeiter** [comment]
This should now be resolved, thanks!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a documentation defect: an internal docs link pointed to a missing page, with no reported SDK runtime behavior change required.

### Evidence
- The OpenAI guide linked `StreamingTextResponse` to an API reference URL that returned a 404.
- The requested change concerns a broken link in the documentation.
- A maintainer confirmed that the issue was resolved.
