### ISSUE TITLE
Support Svelte 4

### ISSUE THREAD

**Issue by onionhammer** [vercel-labs/ai#235]
Currently the peer dependencies are locked to `^3.29.0`

https://svelte.dev/blog/svelte-4#migrating

**Comment by MaxLeiter** [comment]
A pull request addressing this would be great if you're able to contribute

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests support for a new major version of Svelte rather than reporting a failure of existing Svelte 3 behavior.

### Evidence
- The package peer dependency is limited to Svelte `^3.29.0`.
- The issue requests compatibility with the newly released Svelte 4.
- A maintainer invited a pull request to add this support.
