### ISSUE TITLE
Can the messages role be added to the function?

### ISSUE THREAD

**Issue by JohannLai** [vercel-labs/ai#241]
Currently, there are only assistant and user here, unable to express the status of function. I hope the display of function frontend.

![image](https://github.com/vercel-labs/ai/assets/10769405/30a50168-537e-4f56-b9d9-3fbc0c6a473d)

<img width="415" alt="image" src="https://github.com/vercel-labs/ai/assets/10769405/7b008414-2492-465d-9fdc-4456e1c8aab0">

**Comment by JohannLai** [comment]
And this function is same.

![wecom-temp-324804-1b64b8a1c03312a18824b1bf01d9a66b](https://github.com/vercel-labs/ai/assets/10769405/38afe9e5-fb26-4375-85f2-4733d1421cd3)

**Comment by shuding** [comment]
This is now supported via #178.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a new message role and frontend representation for function calls rather than reporting a failure of promised behavior. The later implementation confirms it was a capability enhancement.

### Evidence
- The reporter asks to add a function role/status to frontend messages because only user and assistant roles were available.
- The requested behavior would enable displaying function calls and arguments in the chat UI.
- A maintainer states that this capability became supported via #178.
