### ISSUE TITLE
The chat results are missing scrollbars

### ISSUE THREAD

**Issue by netgfx** [vercel-labs/ai#247]
There is no way to scroll on https://sdk.vercel.ai/prompt to see the results if they are longer than your browser height.

![image](https://github.com/vercel-labs/ai/assets/864248/9cd0ed21-2c31-4b70-9440-fca1dffe5dec)

As you can see there is no scrollbar on the page, so I cannot see the chatgpt3.5 whole response.

**Comment by zixuan945** [comment]
```
document.querySelector("#result").parentElement.parentElement.parentElement.classList.add("relative")
document.querySelector("#result").classList.add('overflow-auto')
document.querySelector("#result").classList.add('absolute')
```
Executing the above code in the console of the developer tools will fix this problem.I can't find the source code for this site, so can't create a pr to fix it.

**Comment by MaxLeiter** [comment]
This should be resolved now, thanks!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete UI failure in the existing prompt playground: long results were inaccessible because scrolling was broken.

### Evidence
- The prompt playground did not provide a scrollbar when generated results exceeded the browser height, preventing users from viewing the full response.
- A commenter supplied a CSS/DOM workaround that restored scrolling.
- A maintainer confirmed that the issue had been resolved.
