### ISSUE TITLE
Audio as input?

### ISSUE THREAD

**Issue by saiabishek1** [vercel-labs/ai#256]
Is it possible to provide an audio file as input instead of text for the chat functionality? 
Currently my workaround is to use the speech-to-text api to get the transcribed text to the client and then send another request with the transcribed text to get the streaming response. 

Ideally, this would be handled in the `useChat` hook with the transcribed text being resent to OpenAI in the API layer rather than from the client.

**Comment by MaxLeiter** [comment]
Transcription is, at least at the moment, out-of-scope. But there's no reason you can't handle the transcription in a route handler / api and pass that off to your LLM provider / the SDK manually.

**Comment by seflless** [comment]
Is this going to be reopened now, now that Text to Speech is available from OpenAI? https://platform.openai.com/docs/guides/speech-to-text

**Comment by sleroq** [comment]
Gemini can take audio as an input as well. 
https://ai.google.dev/gemini-api/docs/audio#inline-data

**Comment by nikshepsvn** [comment]
+1, wanted to use gemini for transcription

**Comment by lgrammel** [comment]
The AI SDK supports audio as input using file parts: https://sdk.vercel.ai/docs/foundations/prompts#example-mp3-audio-file-from-buffer

**Comment by haydenbleasel** [comment]
You can use Orate for this — https://www.orate.dev/

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an audio-input and transcription integration capability rather than reporting broken or undocumented promised behavior. Later support does not change the original request's feature nature.

### Evidence
- The reporter requests direct audio-file input and automatic transcription handling in `useChat`, instead of a client-side two-request workaround.
- A maintainer initially stated transcription was out of scope and suggested implementing it manually in an API route.
- A later maintainer comment notes that audio input is now supported through file parts.
