### ISSUE TITLE
Why I can't npm install the latest version 2.1.13?

### ISSUE THREAD

**Issue by zhaozhiming** [vercel-labs/ai#261]
Greetings everyone,

I recently utilized the `npm install` command to download the `ai` library, however, the version I received was 2.1.9. Upon checking [**registry.npmmirror.com/ai**](https://registry.npmmirror.com/ai), I noticed that the latest version is also 2.1.9. 

I'm curious, has the latest version 2.1.13 not been released yet? 

Any assistance on this matter would be greatly appreciated. Thank you.

**Comment by zhaozhiming** [comment]
Thanks. I use the `registry.npmjs.org` registry and it works.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was a support question caused by a stale third-party npm mirror, not a defect, documentation request, example change, or new AI SDK capability.

### Evidence
- The reporter could not install version 2.1.13 while using registry.npmmirror.com, which only exposed version 2.1.9.
- A commenter verified that versions 2.1.10–2.1.13 were published and installable from the official npm registry; the third-party mirror was behind.
- The reporter confirmed that switching to registry.npmjs.org resolved the issue.
