### ISSUE TITLE
langchain   Error in handler Handler

### ISSUE THREAD

**Issue by AuYuHui** [vercel-labs/ai#267]
- langchain V0.0.102
- ai V2.1.9

```typescript
chain.call({
      question: sanitizedQuestion,
      chat_history: new ChatMessageHistory(history) || [],
    }, CallbackManager.fromHandlers(handlers)).catch((err) => {
      console.error('err', err)
    })
return streamToResponse(stream, event.node.res)
```

 Error in handler Handler, handleChainEnd: TypeError [ERR_INVALID_STATE]: Invalid state: WritableStream is closed
[https://github.com/AuYuHui/nuxt-chat-pdf](project)

**Comment by jaredpalmer** [comment]
Can you upgrade to the latest version of `ai` and confirm this is still happening?

**Comment by AuYuHui2** [comment]
upgrade to the latest version  is ok, no error

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete runtime failure in an existing streaming integration. Although it was already fixed in a newer release, the issue itself describes broken behavior rather than requesting a new capability.

### Evidence
- Using `ai` v2.1.9 with LangChain v0.0.102 caused `TypeError [ERR_INVALID_STATE]: Invalid state: WritableStream is closed` during `handleChainEnd`.
- The reporter confirmed that upgrading to the latest `ai` version eliminated the error.
