### ISSUE TITLE
no responses were shown, just blank white screen

### ISSUE THREAD

**Issue by jiarenlim** [vercel-labs/ai#270]
i encounter one weird problem, i use the starter for the huggingface and nothing pop up on my screen after i ask anything and also no responses from the AI was shown or streamed which im just looking at a blank white screen. But I do check out there are responses from AI in the network tab in dev tools, anyone know why is that? 
![Screenshot 2023-07-03 132740](https://github.com/vercel-labs/ai/assets/67389513/8812af2e-4c34-40e2-9701-79ea6a6a4d8d)

**Comment by zacrafidi** [comment]
+1 same happens with the langchain/openai docs for me

**Comment by mzavattaro** [comment]
Yep same. Something broke in a recent package update. V2.1.9 works whereas v2.1.13 is broken and doesn't output the response from OpenAI. It does return a 200 success response though. Haven't checked versions 2.1.10, 2.1.11 or 2.1.12. 

Can confirm 2.1.9 definitely works still.

**Comment by K0rdan** [comment]
Got the same problem. 2.1.12 is working for me.

**Comment by Rinshin-Jalal** [comment]
2.1.9 is working perfectly for me
2.1.12 is not working ...

**Comment by jiarenlim** [comment]
yup, apparently, versions above 2.1.9 have some errors, i have built one using the hugging face starter using v 2.1.9 and it works, feel free to try it out, it also have a dark mode settings and using abit of  ui component from shadcn.  However, does anybody knows how can i switch the model so i can use a more intelligent model as the current one is not good enough and couldn't answer most of the question I asked. Any help would be highly appreciated! 
feel free to visit the bot =>[https://jeybot.vercel.app/](url)      
![image](https://github.com/vercel-labs/ai/assets/67389513/987b767b-0225-4b16-bdbc-ebf7fd92d2e0)

**Comment by jaredpalmer** [comment]
This has been fixed. Sorry about that.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete regression in existing response rendering/streaming behavior, confirmed across versions and subsequently fixed.

### Evidence
- The starter receives a successful AI response in the network tab, but the UI remains blank and does not stream or display it.
- Multiple users report a version regression: 2.1.9 works while later releases such as 2.1.12/2.1.13 fail.
- A maintainer confirms that the problem was fixed.
