### ISSUE TITLE
Make streaming utility function for Azure openai service

### ISSUE THREAD

**Issue by Cenrax** [vercel-labs/ai#279]

**Comment by ovived** [comment]
Anything updated here?

**Comment by MaxLeiter** [comment]
I don't believe there's anything for us to provide? See https://github.com/dan-kwiat/openai-edge/issues/8#issuecomment-1634334338

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **Medium**

### Rationale
The issue requests new Azure OpenAI streaming support or utility functionality rather than reporting a concrete failure in existing behavior.

### Evidence
- The title requests a new streaming utility function for the Azure OpenAI service.
- No existing broken or contradictory SDK behavior is described.
- A maintainer indicated there may be nothing for the SDK project to provide, but did not identify a current bug.
