### ISSUE TITLE
LangChainStream Cannot be used for tools

### ISSUE THREAD

**Issue by AuYuHui2** [vercel-labs/ai#281]
It will output the process

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This describes a concrete failure or incorrect output when using an existing streaming API with LangChain tools, despite the limited reproduction details.

### Evidence
- The title reports that the existing `LangChainStream` API cannot be used with tools.
- The description says it outputs the tool execution process rather than the expected result.
