### ISSUE TITLE
Streaming does not work once deployed

### ISSUE THREAD

**Issue by GavanWilhite** [vercel-labs/ai#283]
I'm having an issue where streaming works perfectly fine when running locally, but after deploying it only returns the results all at once.

This is using `streamToResponse` in a normal serverless function (not an edge function).

**Comment by pangao66** [comment]
https://github.com/vercel-labs/ai/issues/239

**Comment by MaxLeiter** [comment]
Closing as a dupe of #239

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the description reports broken deployed streaming, the issue was explicitly handled as duplicate bookkeeping, which falls under none.

### Evidence
- The reporter says `streamToResponse` streams locally but returns the entire result at once after deployment in a serverless function.
- A maintainer closed the issue as a duplicate of #239.
