### ISSUE TITLE
Cannot find module 'ai/svelte'

### ISSUE THREAD

**Issue by TGlide** [vercel-labs/ai#291]
# Steps to reproduce
- Clone vercel-labs/ai
- cd into `ai/examples/sveltekit-openai`
- Run `npm install`
- Run `npm run dev`
![image](https://github.com/vercel-labs/ai/assets/26071571/42aa9c13-f6b7-4338-ac0c-a4f27ed8b419)

**Comment by MaxLeiter** [comment]
This is now resolved

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete runtime/build failure in an existing example caused by an unresolved AI SDK module, so it is a bug rather than a request for new example content.

### Evidence
- Following the repository's SvelteKit example setup caused Vite to fail resolving the existing `ai/svelte` import.
- The attached output shows `Cannot find module 'ai/svelte'` during SSR evaluation.
- A maintainer later confirmed the issue was resolved.

**Comment by TGlide** [comment]
Why is this being pinged 3 years after it was resolved?

**Comment by gr2m** [comment]
public auditing of automation we are adding to the AI SDK. Apologies for the noise. I don't expect further pings on closed issues or PRs. Feel free to unsubscribe from this one. Thanks for your help, we love Svelte!
