### ISSUE TITLE
AI SDK with multiple inputs

### ISSUE THREAD

**Issue by reveurguy** [vercel-labs/ai#310]
In the example with Open AI, we use ChatHelpers with the useChat() function to handle input from the user.
Is there any way to handle multiple inputs in the same way.
I have the same code as the repo, but now i want to add more inputs to my application. I can handle that using states normally but wanted to know if there is some way to handle it with useChat().

Also if i use state management for additional inputs, would that work with the ChatHelpers function, because the handleSubmit part is being used with that. How would i pass the additional input data to the prompt call?

**Comment by MaxLeiter** [comment]
You can modify the `body` and `headers` in `useChat`/`useCompletion` and access them in your API. 

```
// client
const { } = useChat({ body: { myCustomValue: valueFromState })

// server
const { myCustomValue } = await req.body()
```

**Comment by reveurguy** [comment]
This way doesnt seem to work.

<img width="436" alt="Screenshot 2023-07-16 at 10 12 12 PM" src="https://github.com/vercel-labs/ai/assets/59417546/b6b522f6-57f3-4cff-8518-0583873db285">

This is the call

Getting this error on api file
<img width="920" alt="Screenshot 2023-07-16 at 10 17 07 PM" src="https://github.com/vercel-labs/ai/assets/59417546/e32eedcb-575a-4dcb-9f15-6ba8fb5e258a">


Tried to use NextApiRequest and some other ways as well but didn't get any response from the completion.
I am not using the handleSubmit on a form, just calling it inside a function which checks some stuff, Can that be the issue?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily an implementation/support question rather than evidence that an existing AI SDK capability is broken or missing.

### Evidence
- The reporter asks how to pass multiple state values through useChat/useCompletion.
- A maintainer explains that custom values can be supplied through the body option and read in the API handler.
- The follow-up shows a TypeScript error from calling req.body() on a Web Request, whose body is a stream property, and asks for implementation help.
