### ISSUE TITLE
callback functions aren't invoked unless you wrap the AIStream

### ISSUE THREAD

**Issue by d-haxton** [vercel-labs/ai#313]
Example: 

```
OpenAIStream(response, {
            onStart: async () => {
              // this DOES get invoked
              console.log("started stream");
            },
            onToken: async (token) => {
              // never invoked
            },
            onCompletion: async (completion) => {
              // never invoked
            },
          });
```

But if you just wrap it like:

```
const stream = OpenAIStream(response, {
 ...
});
const streamingResponse = new StreamingTextResponse(stream);
const text = await streamingResponse.text();
console.log(text);
```

Then the callback handlers work. The frustrating thing is that `onStart` works, so you would expect the other two to also be invoked ... if this started, but it doesn't. Which isn't very obvious (if documented at all). Either way if it's a bug or just undocumented behavior, would be nice if there was a way to only work with the cbs.

**Comment by MaxLeiter** [comment]
You need to pipe data through the OpenAI Stream (which is a `TransformStream` under the hood). If you stream your results to the client with StreamingTextResponse that will happen for you. Otherwise you can do something like this:

```
const reader = stream.getReader();
while (true) {
  const { done, value } = await reader.read();
  if (done) break;
}
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question about lazy stream consumption. The comments clarify expected behavior and provide an existing solution, without establishing a product bug or a concrete documentation change request.

### Evidence
- The callbacks run when the returned OpenAIStream is consumed through StreamingTextResponse.
- A maintainer explains that OpenAIStream is a TransformStream and must be read or piped for onToken and onCompletion to execute.
- The maintainer provides a getReader().read() loop as the supported way to consume the stream without StreamingTextResponse.
