### ISSUE TITLE
Configure the basePath to be a different value rather chat.openai.com

### ISSUE THREAD

**Issue by Cenrax** [vercel-labs/ai#319]
It will be great if we can set the basePath with user input rather than a fixed value.

Advantages:
1. It will help in using the sdk for using other openai deployments which are set in different environments

**Comment by MaxLeiter** [comment]
You can pass the `basePath` into the `Configuration` from `openai-edge` in your server handler.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The requested capability already exists, so the issue is effectively a usage/support question rather than a bug or new feature request.

### Evidence
- The issue requests user-configurable `basePath` support for alternate OpenAI deployments.
- A maintainer explains that this is already supported by passing `basePath` to the `openai-edge` `Configuration` in the server handler.
