### ISSUE TITLE
example code when implementing functions using page router

### ISSUE THREAD

**Issue by onlyrandomguy** [vercel-labs/ai#322]
the example code in the repo uses the app router - would you happen to have examples using the page router? can't seem to figure out implementation. thanks!

**Comment by MaxLeiter** [comment]
Something like this should work

```
const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY
})

const openai = new OpenAIApi(config)

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const aiResponse = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages: [{ role: 'user', content: 'What is love?' }]
  })

  const stream = OpenAIStream(aiResponse, { 
    experimental_onFunctionCall: async (functionCallPayload, createFunctionCallMessages) => {
        const result = await myFunction(functionCallPayload)
   
        return await openai.createChatCompletion({
          model: 'gpt-3.5-turbo-0613',
          stream: true,
          // Append the relevant "assistant" and "function" call messages
          messages: [...messages, ...createFunctionCallMessages(result)],
          functions,
        })
      }
  })


  return streamToResponse(stream, res)
}
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The issue primarily requests an additional implementation example for a different Next.js router, rather than reporting established broken behavior.

### Evidence
- The requester asks for example code implementing function calls with Next.js Pages Router because existing repository examples use App Router.
- The maintainer provides a tentative Pages Router sample and offers to update the documentation if it works; no concrete SDK failure is confirmed.
