### ISSUE TITLE
npm install fails for ai@2.1.8 due to conflicting peerOptional svelte peer dependency

### ISSUE THREAD

**Issue by crucialfelix** [vercel-labs/ai#354]
Hello!

I am using Next.js and ai@2.1.8

npm install fails with Conflicting peer dependency

```
npm ERR!
--
17:47:40.722 | npm ERR! While resolving: ai@2.1.8
17:47:40.722 | npm ERR! Found: svelte@4.1.0
17:47:40.722 | npm ERR! node_modules/svelte
17:47:40.722 | npm ERR!   peer svelte@"^4.0.0" from sswr@1.11.0
17:47:40.722 | npm ERR!   node_modules/sswr
17:47:40.722 | npm ERR!     sswr@"^1.10.0" from ai@2.1.8
17:47:40.722 | npm ERR!     node_modules/ai
17:47:40.723 | npm ERR!       ai@"2.1.8" from the root project
17:47:40.723 | npm ERR!
17:47:40.723 | npm ERR! Could not resolve dependency:
17:47:40.723 | npm ERR! peerOptional svelte@"^3.29.0" from ai@2.1.8
17:47:40.723 | npm ERR! node_modules/ai
17:47:40.723 | npm ERR!   ai@"2.1.8" from the root project
17:47:40.723 | npm ERR!
17:47:40.723 | npm ERR! Conflicting peer dependency: svelte@3.59.2
17:47:40.723 | npm ERR! node_modules/svelte
17:47:40.723 | npm ERR!   peerOptional svelte@"^3.29.0" from ai@2.1.8
17:47:40.724 | npm ERR!   node_modules/ai
17:47:40.724 | npm ERR!     ai@"2.1.8" from the root project
17:47:40.725 | npm ERR!
17:47:40.725 | npm ERR! Fix the upstream dependency conflict, or retry
17:47:40.725 | npm ERR! this command with --force or --legacy-peer-deps
17:47:40.725 | npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I'm not using svelte, but the error above is about peer dependency svelte 4 vs 3.29

Locally I can use `npm i --force` which works

I customized vercel build to use that as well:
https://vercel.com/docs/concepts/deployments/configure-a-build

Thank you!

**Comment by MaxLeiter** [comment]
Please try updating to `ai@2.1.22`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete package installation failure caused by conflicting peer dependency declarations in an existing AI SDK release.

### Evidence
- Installing ai@2.1.8 fails because its optional Svelte 3 peer dependency conflicts with sswr's Svelte 4 peer dependency.
- The reporter must use npm's --force option as a workaround despite not using Svelte.
- A maintainer recommends upgrading to ai@2.1.22, indicating the dependency issue may have been fixed in a later release.
