### ISSUE TITLE
Azure not supporting functions ? 

### ISSUE THREAD

**Issue by thareekanvarm** [vercel-labs/ai#361]
![Screenshot from 2023-07-21 12-08-27](https://github.com/vercel-labs/ai/assets/117096530/f317e64d-861d-4845-9c83-fe380a4d892b)

some one please help me .. or give me a solution

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support question about Azure OpenAI configuration or API-version support, rather than a confirmed AI SDK defect or a request for a specific product change.

### Evidence
- The report asks for help with Azure OpenAI function calling.
- The screenshot shows Azure returning `invalid_request_error: Unrecognized request argument supplied: functions`.
- No evidence establishes that the AI SDK itself is violating documented behavior.
