### ISSUE TITLE
Add completion readable store (and equivalent for frameworks other than svelte) to useChatHelpers

### ISSUE THREAD

**Issue by yehiaabdelm** [vercel-labs/ai#364]
It would be very useful to have a variable we can use to track the current completion being streamed for useChat.

**Comment by MaxLeiter** [comment]
Can you not inspect the messages?

**Comment by yehiaabdelm** [comment]
Yeah I tired that but had some issues with the store initially showing the last user message. Ended up using useCompletion and the completion readable store while sending my custom body with the messages.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an additional helper/store for tracking streamed chat completion rather than identifying a violation of documented existing behavior. It is an API ergonomics enhancement.

### Evidence
- The requester asks for a variable in `useChatHelpers` that directly tracks the currently streamed completion.
- The maintainer suggests accessing the last item in `messages`; the requester reports an initial user-message state and instead uses `useCompletion` as a workaround.
