### ISSUE TITLE
Feedback for “Getting Started”

### ISSUE THREAD

**Issue by EmilienKopp** [vercel-labs/ai#373]
Is it me or the `config` constant is declared twice ?

https://sdk.vercel.ai/docs/getting-started#create-an-api-route  (SvelteKit)

```
// Create an OpenAI API client (that's edge friendly!)
const config = new Configuration({
  apiKey: OPENAI_API_KEY,
});
const openai = new OpenAIApi(config);
 
// Set the runtime to edge for best performance
export const config = {
  runtime: 'edge'
};
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This reports an erroneous documentation snippet with a duplicate constant declaration, so it is a documentation issue rather than a product behavior bug.

### Evidence
- The SvelteKit Getting Started snippet declares `const config` and later `export const config` in the same scope.
- The requested correction concerns code shown in the documentation.
