### ISSUE TITLE
chatRequest options are not sent to /api/chat

### ISSUE THREAD

**Issue by ildella** [vercel-labs/ai#378]
My code has

```js

  const {
    messages,
    append,
  } = useChat({body: {first: 'abc'}})

....
  const handleSubmit = async (event) => {
  ....
    append({
      content: inputValue,
      role: 'user',
      createdAt: new Date(),
    }, {body: {second: '123'}})
    ....
```

in my `/api/chat` POST handler, I receive `first` but I do not receive `second`. 
I've figure that out looking at svelte/use-chat.ts which at line 91 has

`...chatRequest.options?.body,`

See: https://github.com/vercel-labs/ai/blob/main/packages/core/svelte/use-chat.ts#L91

What am I missing? 
If not supported, it would be great to have additional body params in the append() and not only at useChat().

**Comment by ildella** [comment]
Got that, is `{options}`

```js
    const options = {body: {chatId}}
    append({
      content: inputValue,
      role: 'user',
      createdAt: new Date(),
    }, {options})
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a resolved usage question about the required `append` argument structure, not a product defect or request for a change.

### Evidence
- The reporter passed `body` directly as the second argument to `append`.
- A follow-up comment states the correct supported shape is `{ options: { body: { chatId } } }`, resolving the issue as usage rather than broken behavior.
