### ISSUE TITLE
Client Side for LocalStorage

### ISSUE THREAD

**Issue by satpalsr** [vercel-labs/ai#382]
I want to use localstorage with [vercel ai-chatbot](https://github.com/vercel-labs/ai-chatbot), but api/chat/route.ts is a server side code.
A call to this api endpoint is made via useChat handleSubmit() which in turns call getStreamedResponse() and [make a post request to api endpoint](https://github.com/vercel-labs/ai/blob/4c05f5b935b649f31bfce43c0ef0ef5d6ec29ee0/packages/core/react/use-chat.ts#L85).

Now, as I want to use localstorage at api/chat/route, I also need to make ai-sdk code client side.
Since, otherwise I get Attempted to call POST() from the server but POST is on the client. It's not possible to invoke a client function from the server

Also created the same [issue on vercel ai-chatbot](https://github.com/vercel-labs/ai-chatbot/issues/115)

**Comment by MaxLeiter** [comment]
This library won't support making the API requests on the client as that requires exposing your API key(s) to the browser.

What are you trying to accomplish?

**Comment by satpalsr** [comment]
Hey @MaxLeiter,

I am creating a client side chat ui application only where users can use their own api key & use their own browser local storage. Though no problem now, I moved local storage to chat panel & it seems to be working fine.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a resolved support/design question rather than a concrete SDK defect or an active request for a product change.

### Evidence
- The reporter wanted browser-side LLM requests to use a user-provided API key and localStorage.
- A maintainer stated that client-side LLM API requests would not be supported because they expose API keys.
- The reporter moved localStorage handling into the chat panel and confirmed the approach was working.
