### ISSUE TITLE
Streaming issue while changing chats

### ISSUE THREAD

**Issue by ExLineP** [vercel-labs/ai#386]
Facing and issue when createChatCompletion and useChat. When typing prompt and sending it to get streaming response, switching to another chat copies all messages from previous chat and also copies not completed streaming response. Does this SDK covers the subject of using more than one chat or is it really a bug?

**Comment by MaxLeiter** [comment]
Closing in favor of #387

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The report describes concrete incorrect behavior when using multiple chats during streaming. Duplicate closure does not change the underlying report from a bug.

### Evidence
- Switching to another chat while a response is streaming reportedly copies the previous chat’s messages and incomplete streamed response into the new chat.
- The issue was closed in favor of #387, indicating the behavior was tracked elsewhere as a duplicate.
