### ISSUE TITLE
Add Replicate

### ISSUE THREAD

**Issue by satpalsr** [vercel-labs/ai#389]
Here's a [llama chat streaming example with replicate](https://github.com/replicate/llama-chat)
Guide for[ streaming](https://replicate.com/docs/streaming)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new Replicate provider/streaming support, which is a new capability rather than a bug, documentation-only change, or example correction.

### Evidence
- The title explicitly requests adding Replicate.
- The description links to Replicate's Llama chat streaming example and streaming guide, indicating desired provider integration or support.
- No existing AI SDK behavior is reported as broken.
