### ISSUE TITLE
Feedback for “AIStream”

### ISSUE THREAD

**Issue by BSolo13** [vercel-labs/ai#392]
AIStreamParserOptions is not inside the 'ai' module after installing 'ai' and 'openai-edge' (pnpm install ai openai-edge). When trying to write code similar to that shown in the example of the AIStream page, I can't successfully import the type. When I check what is inside the module, the type is listed nowhere, the closest thing being the type 'AIStreamParser', which has none of the properties utilized in the example code.

**Comment by MaxLeiter** [comment]
I've updated the docs to reflect the current API. Thanks!

**Comment by BSolo13** [comment]
I'm sorry if this is a stupid question. I'm still new to this. But how do I get the changes you made to affect my code. Its a local project I based of the Vercel SDK through this link: https://sdk.vercel.ai/docs/getting-started. Im using AIStream to turn a response from a non-openAI request into something that OpenAIStream can interpret correctly. In doing so, I used the example from https://sdk.vercel.ai/docs/api-reference/ai-stream as my base. Here is where importing AIStreamParserOptions fails. I've reinstalled and updated the ai package but that didn't do it (as I'm sure is obvious to you) Thanks for your help

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The reported failure came from an outdated API documentation example rather than broken SDK behavior, and the maintainer addressed it with a docs correction.

### Evidence
- The AIStream documentation example referenced `AIStreamParserOptions`, which was not exported by the installed `ai` package.
- A maintainer confirmed the resolution was to update the documentation to reflect the current API.
