### ISSUE TITLE
"Error: Not found" On production .

### ISSUE THREAD

**Issue by m4rcelpl** [vercel-labs/ai#395]
Hi, This error only occurs in production. When I access the page with the added:

``` js
const { messages, handleSubmit, input } = useChat({
        api: "/chat",
    });
```
An error appears in the logs:
`Error: Not found: /chat%7Cchat-1-loading`
Everything works fine but this is annoying. 

Sveltekit on Node.

**Comment by MaxLeiter** [comment]
It should be `api/chat`, right?

**Comment by m4rcelpl** [comment]
Hi, No.  
api/chat are default, but I have rout /chat and this is work. But I don’t know why it try to connect to not existing one: ‘/chat|chat-1-loading’ and trigger error.

**Comment by MaxLeiter** [comment]
Ah, this is a small bug introduced in 3d2979910847db5cfc0b36780b7017fbf8af5f5b. Fix incoming.

**Comment by genu** [comment]
I'm still seeing this as an issue in vue. I'm using version `2.2.8`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports an unintended production request and error caused by a confirmed regression in existing SDK behavior.

### Evidence
- Using `useChat({ api: "/chat" })` in production triggers an unexpected request/error for `/chat%7Cchat-1-loading`.
- A maintainer explicitly identified the behavior as a small bug introduced by commit `3d2979910847db5cfc0b36780b7017fbf8af5f5b` and said a fix was incoming.
- A later commenter reported the issue still occurring with Vue in version `2.2.8`.
