### ISSUE TITLE
Feedback for “OpenAI”

### ISSUE THREAD

**Issue by PrinceBaghel258025** [vercel-labs/ai#428]
error unhandledRejection: Error: Request failed with status code 400 and body 
`{"error":{"message":"This model's maximum context length is 8192 tokens. However, your messages resulted in 8312 tokens. Please reduce the length of the messages.","type":"invalid_request_error","param":"messages","code":"context_length_exceeded"}}
`
- using LangChainStream method to get the stream and handlers and passing to ChatOpenAI.call
how can i handle above error while using streams

**Comment by MaxLeiter** [comment]
You should write something that truncates text if it's too large. You can use something like https://www.npmjs.com/package/@dqbd/tiktoken and its lite functionality for working with edge functions. We hope to ship support for this eventually.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support question about handling an upstream model token-limit error. The maintainer describes a user-side workaround and only mentions possible future SDK support.

### Evidence
- The 400 response is OpenAI's documented context-length limit: the messages total 8312 tokens for an 8192-token model.
- The reporter asks how to handle the error while streaming rather than identifying a promised AI SDK behavior that failed.
- The maintainer recommends truncating input with a tokenizer and notes that built-in support may be added eventually.
