### ISSUE TITLE
Next-openai app is not working

### ISSUE THREAD

**Issue by iramykytyn** [vercel-labs/ai#442]
I wanted to install and run `next-openai` app locally. So I've cloned the latest version of the repo and run steps from README but I'm getting the error `./app/page.tsx:3:0
Module not found: Can't resolve 'ai/react'`:

<img width="648" alt="Screenshot 2023-08-12 at 16 23 02" src="https://github.com/vercel-labs/ai/assets/6651168/834fd6f7-13f1-4bcd-ba3a-64fa8e83070c">

Is some step missing in the README? 

<img width="945" alt="Screenshot 2023-08-12 at 16 32 23" src="https://github.com/vercel-labs/ai/assets/6651168/4bab947c-17f9-4d76-8770-568e49a64121">

**Comment by iampava** [comment]
I was just looking at this and it works following the instructions here: https://sdk.vercel.ai/docs/getting-started

Looking at your image, I see some Nuxt related things which are weird. Try again in a new folder using the instructions in the link above.

**Comment by MaxLeiter** [comment]
I verified it works locally on my end. @iampava the `nuxt` logs are from running `pnpm` in the monorepo -- it installs all the dependencies by default.

@iramykytyn can you double-check you ran `pnpm i` in the examples folder?

**Comment by xiaojinwhu** [comment]
I discovered the problem because I ran 'pnpm install' directly in the example folder of the entire ai project, so some dependencies referenced local packages within the ai project. Copying the project inside the example folder out and re-executing it should solve the issue."

Specifically, your solution steps are:

Realizing that the problem stems from running pnpm install directly in the example directory of the entire ai project, causing some dependencies to reference local packages within the ai project itself.

Copying (cp) the project inside the example folder to a separate directory.

Re-executing pnpm install in the new project directory to install dependencies.

The problem is resolved, and the missing module dependencies no longer appear.
@iramykytyn

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **Medium**

### Rationale
The report concerns a runnable example project's installation and dependency setup rather than a confirmed defect in the AI SDK itself. It indicates the example or its setup instructions may need correction, though reproduction is inconsistent.

### Evidence
- The cloned `examples/next-openai` project fails to compile with `Module not found: Can't resolve 'ai/react'` after following its README.
- A later commenter attributes the failure to monorepo-local package references and reports that copying the example outside the repository and reinstalling dependencies resolves it.
- A maintainer could not reproduce the failure and asked whether installation was run in the correct folder.
