### ISSUE TITLE
Promp engineering section of the docs suggests a "temperature" of 1 would vary the output every time. However, it's the same

### ISSUE THREAD

**Issue by iampava** [vercel-labs/ai#445]
### Demo:
https://github.com/vercel-labs/ai/assets/11327761/be840a85-5098-4aad-962a-3688c70348d0

### Expected result
I expected to get different results. But it always generates: `"Java and Jams", "Caffeinated Concerts", "Musical Brews" `.

**Comment by MaxLeiter** [comment]
Thank you! this was a result of our LLM response caching -- I added an override for this example.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete behavioral failure in an existing interactive documentation example, caused by response caching rather than merely unclear written documentation.

### Evidence
- The prompt engineering docs demo returned the same generated names despite indicating that temperature 1 should vary output.
- The maintainer confirmed LLM response caching caused the behavior and added an override for the example.
