### ISSUE TITLE
Broken links to /api-reference

### ISSUE THREAD

**Issue by jordienr** [vercel-labs/ai#56]
Problem:
There are some broken links in the docs, here are two I found. 

- Page: https://sdk.vercel.ai/docs/guides/openai
- Link 1: OpenAIStream - https://sdk.vercel.ai/api-reference#openaistream
- Link 2: StreamingTextResponse - https://sdk.vercel.ai/api-reference#streamingtextresponse

Hope this is helpful.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a documentation issue because it reports broken API-reference links in a docs page, with no SDK behavior change required.

### Evidence
- The documentation guide links for `OpenAIStream` and `StreamingTextResponse` point to broken `/api-reference` anchors.
- The requested change concerns correcting links in the published documentation.
