### ISSUE TITLE
`docs` segment is missing when navigate using a link

### ISSUE THREAD

**Issue by A7med3bdulBaset** [vercel-labs/ai#65]
This [Link](https://github.com/A7med3bdulBaset/ai/blob/f449ece2da38175f505742d8ae020910e7975e7a/docs/pages/docs/guides/openai.mdx?plain=1#L158):
```markdown
We can use the [`useCompletion`](/api-reference/use-completion) hook to make it easy to wire up the UI.
```

leads to:
https://sdk.vercel.ai/api-reference/use-completion
which is not found

instead of:
https://sdk.vercel.ai/docs/api-reference/use-completion

**Comment by jaredpalmer** [comment]
This is fixed now. Thanks for filing!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The issue reports an incorrect internal link in the documentation, requiring a docs correction rather than a product behavior change.

### Evidence
- A documentation link points to `/api-reference/use-completion`, producing a not-found page instead of `/docs/api-reference/use-completion`.
- The maintainer confirmed the broken link was fixed.
