### ISSUE TITLE
What about Serverless Functions?

### ISSUE THREAD

**Issue by NickHeiner** [vercel-labs/ai#67]
The docs talk about using these tools in the context of an edge function in a NextJS app. What if I want a standalone Serverless Function?

**Comment by jaredpalmer** [comment]
It works perfectly! Be mindful of costs depending on your provider. Edge functions might be significantly cheaper (and faster).

**Comment by NickHeiner** [comment]
Actually, never mind – I figured it out. I think the issue is just that I wasn't setting `max_tokens` in my code, but the Playground defaulted it to 200.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The actionable request is to expand the documentation with guidance or an example for standalone Serverless Functions, rather than change SDK behavior.

### Evidence
- The issue asks how to use the SDK with a standalone Serverless Function because the documentation focuses on Next.js edge functions.
- The reporter explicitly says adding an example to the documentation would be helpful.
- The apparent truncated-stream problem was resolved as a missing `max_tokens` setting, so no SDK failure remained.
