### ISSUE TITLE
Copying from the docs copies borken text

### ISSUE THREAD

**Issue by omar2205** [vercel-labs/ai#93]
For example, if I tried to copy `buildOpenAssistantPrompt` function I get this

```ts
function
 
buildOpenAssistantPrompt
(
  messages
:
 { content
:
 
string
; role
:
 
'system'
 
|
 
'user'
 
|
 
'assistant'
 }[]
) {
  
return
 (
    messages
      
.map
(({ content
,
 role }) 
=>
 {
        
if
 (role 
===
 
'user'
) {
          
return
 
`<|prompter|>
${
content
}
<|endoftext|>`
;
        } 
else
 {
          
return
 
`<|assistant|>
${
content
}
<|endoftext|>`
;
        }
      })
      
.join
(
''
) 
+
 
'<|assistant|>'
  );
}
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This requests correction of how code is presented or copied from the documentation, rather than a product behavior change.

### Evidence
- Copying the `buildOpenAssistantPrompt` function from the documentation produces malformed code with excessive whitespace and line breaks.
- The reported problem is confined to copying a documentation code sample; no AI SDK runtime behavior is described as failing.
