### ISSUE TITLE
CallbackManager in langchain is deprecated

### ISSUE THREAD

**Issue by mohamedcherifmo** [vercel-labs/ai#94]
In the langchain example it's using callBackManager to get the handlers, this is now deprecated and should be replaced with handlers

i.e. the following line:
```
callbackManager: CallbackManager.fromHandlers(handlers)
```
should be replaced with:
```
 callbacks: [handlers],
```

**Comment by mohamedcherifmo** [comment]
If you'd like I can submit a PR for this?

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
This is a request to correct outdated code in an existing example rather than change AI SDK product behavior.

### Evidence
- The LangChain example uses the deprecated `CallbackManager` API.
- The requested change updates sample code to use handlers instead.
- A maintainer asked the reporter to submit a PR for the example update.
