### ISSUE TITLE
Feedback for “Getting Started”

### ISSUE THREAD

**Issue by abhi375** [vercel-labs/ai#98]
To enhance user experience, it would be beneficial to allow for user preference-based Tabs for the "Next/Sveltekit" framework. For instance, if a user chooses Sveltekit, the default tab selected in subsequent code snippets should be Sveltekit.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a request to improve documentation-site tab behavior and usability within the Getting Started guide, so it is best classified as documentation.

### Evidence
- The issue proposes remembering a user's Next/SvelteKit tab preference across subsequent documentation code snippets.
- It requests an improvement to the Getting Started documentation experience rather than reporting broken SDK behavior.
